### ISSUE TITLE
Tournament Issues tracking

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#3977]
Reminder for what I should try to fix for the upcoming QOT24

Easy to resolve:
- [x] Difficulty name is missing max width
- [x] Difficulty name and rating color does not get effected by rating

Harder to resolve:
- [x] MP Results when spectating are wrong (due to virtual player) 
- [x] Spectating already started lobby

Site issues:
- [x] View scores should not show the team mode
- [ ] Live score updating is not working properly
Reason: we never provide "sc" to redis, which makes the API return null always
https://github.com/Quaver/Z/blob/e28ef99c8df6b4b3553fe17ead376a43e3fdcb34/multiplayer/redis.go#L137
Also we need to add if check to only send those to redis when tournament mode is enabled.
