### ISSUE TITLE
Next Client Development Goals

### ISSUE THREAD

**Issue by AiAe** [Quaver/Quaver#4169]
- [ ] Setup new Beta branch (Steam and GitHub)
- [ ] Fix submodules (server.client, server.common) so we can rebase from canary to develop branch
- [ ] Update MonoGame to use the latest version
- [ ] Update Wobble - to work with latest MonoGame
- [ ] Update Wobble to use builded MonoGame instead submodule
- [ ] Update all projects to use latest DotNet 8
- [ ] Update all projects to use latest C# version
- [ ] Resolve all warnings/errors that the IDE/builder complains about

**Comment by AiAe** [comment]
# Bugs 
List of reported issues that we should look into fixing
- [ ] https://github.com/Quaver/Quaver/issues/4579 - might not be as simple fix after discussion in the MG community
- [ ] https://github.com/Quaver/Quaver/issues/3907
- [ ] https://github.com/Quaver/Quaver/issues/3922
- [ ] https://github.com/Quaver/Quaver/issues/4420

**Comment by A6sT** [comment]
# Bugs 
- [ ] Various reported crashes
- [ ] Fix "R" keybind being used to swap to mines and resnap notes in the editor <--- warn for duplicate keybinds when multiple action are triggered at the same time
- [ ] Fix Replays displaying player's hits before the notes actually spawns if "Show hits" is enabled before the replay started
# Features
## Song Select
- [ ] Tournament Playlists (see #4786)
## Options
- [ ] #4079 <- will be in skinning v2
# Future stuff i want to work on
- PvM + Infinite mode

**Comment by TDMG-NL** [comment]
# Bugs

#### PR #4679
- [x] #4383 
- [x] #4505 
- [x] #4600

#### PR #4707 
- [x] #3907 

#### Working on
- [ ] #4420 

# Features

#### PR #4719
- [x] #4713 

#### Working on
- [ ] Hover focus

#### On hold
- [ ] Adding teams to multiplayer
